### PR TITLE
Adds HSL Support

### LINKED ISSUE #2: Add support for HSL
This includes creating a color object from HSL and converting into HSL.

### PR DESCRIPTION
**Pull request by stephenoldham**
Well well...HSL 😳

See what you think fella. First stab at an implementation. Don't ask me to explain the algorithm!

    Color::hsl(60, 100, 50); // Color instance (yellow)
    Color::hsl(60, 100, 50, .75); // Color instance (yellow with alpha)
    Color::hex('ff0')->toHsl(); // [60, 100, 50]

Reference for colorspace conversion algorithm:
https://www.niwa.nu/2013/05/math-behind-colorspace-conversions-rgb-hsl/

Resolves #2

### CODE REVIEW

**Comment by stephenoldham** [comment]
Obvs feel free to bin this dude if you're already working on an implementation 😉👍🏼

**Comment by ryangjchandler** [comment]
> Obvs feel free to bin this dude if you're already working on an implementation 😉👍🏼

Sorry @stephenoldham - will get to this one at the weekend!

**Comment by stephenoldham** [comment]
> Sorry @stephenoldham - will get to this one at the weekend!

Oh no worries at all mate, just didn't want you to feel obligated by me sticking my oar in 😆😉

**Review by ryangjchandler — CHANGES_REQUESTED** [review]
@stephenoldham - all looks good! Only thing missing is some documentation in the README file, just a small example needed on how to use the different methods.

**Comment by stephenoldham** [comment]
> @stephenoldham - all looks good! Only thing missing is some documentation in the README file, just a small example needed on how to use the different methods.

Sorry dude, busy weekend. Sorted 👍🏼

**Review by ryangjchandler — APPROVED** [review]

**Pull request merged**
