### PR TITLE
Add missing return types

### PR DESCRIPTION
**Pull request by thinkverse**
Hello again. 🙂

This PR adds return types to functions that are missing ones. 👍 &nbsp;Also, question, phpdocs, yay or nay? 🤔

### CODE REVIEW

**Comment by ryangjchandler** [comment]
@thinkverse Thanks, appreciate it! TE the doc blocks, generally speaking I avoid them unless they add some sort of static analysis benefit which I think they could here, especially with the `toArray` method returning an array of integers.

**Comment by thinkverse** [comment]
> generally speaking I avoid them unless they add some sort of static analysis benefit which I think they could here, especially with the `toArray` method returning an array of integers.

Should I added 'em here or maybe open another PR?

**Comment by ryangjchandler** [comment]
Here is fine. I think just adding return types in the docblocks is fine too, no need to add method descriptions etc.

**Comment by thinkverse** [comment]
Already had them prepared if you're OK with a small one-line description on the methods, can remove the descriptions though if you prefer, it's up to you. 🙂

Screen Shot 2021-01-22 at 1 46 36 PM

**Comment by ryangjchandler** [comment]
That's perfect!

**Comment by thinkverse** [comment]
There ya' go. 👍

**Pull request merged**
